### ISSUE TITLE
The iPad 2020 cannot open the screen expansion function.

### ISSUE THREAD

**Issue by geekhall-PennyPeng** [khanhduytran0/TrollPad#10] opened 2024-02-24 20:14 UTC
Please help research how to enable full version foreground scheduling on iPad Pro 2020. The iPad 2020 cannot open the screen expansion function.

**Comment by geekhall-PennyPeng** [comment] 2024-02-24 20:22
Using this method, the iPad Pro cannot enable full-screen expansion with Stagemanage.

**Comment by khanhduytran0** [comment] 2024-02-26 10:59
I’m sorry but I don’t know how to do so on 16-16.1.2 yet

**Comment by khanhduytran0** [comment] 2024-02-26 10:59
Duplicate of #8

**Closed by khanhduytran0** 2024-02-26 10:59 UTC

**Comment by cslaviero** [comment] 2024-05-08 20:44
> I’m sorry but I don’t know how to do so on 16-16.1.2 yet

could TrollPad modify /var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches/com.apple.MobileGestalt.plist perhaps?

like they suggest here: https://www.reddit.com/r/jailbreak/comments/18kf2ah/how_to_enable_stage_manager_and_unlock_external/ 

Also, would it work on ipadOS 17+ ?
